Remove fee-rates periodic syncing functionality (feature)
horizontalsystems/blockchain-fee-rate-kit-android pull request #17
Opened 2019-11-05 11:37 UTC by nk-the-crazy

- Remove fee-rates periodic syncing feature
- Add fallback fee-rates provider with custom interval based on Coins.
- Close #16

2019-11-05 12:44 UTC, mNizhurin requested changes

2019-11-05 12:44 UTC, mNizhurin commented on feeratekit/src/main/kotlin/io/horizontalsystems/feeratekit/model/FeeRate.kt
>      fun defaultRate(): FeeRate {
We don't need default rates anymore?

2019-11-05 12:44 UTC, mNizhurin commented on feeratekit/src/main/kotlin/io/horizontalsystems/feeratekit/model/FeeRate.kt
> +        val fallbackDataExpiration: Int) {
I think better place for expiration time would be in the BaseFeeRateProvider. Coin knowing about expiration time of FeeRate looks strange to me.

2019-11-06 05:28 UTC, rafaelekol commented on app/src/main/java/io/horizontalsystems/feeratekit/demo/MainViewModel.kt
> +    val rates = MutableLiveData<FeeRate>()
Maybe we should better rename rates to feeRate

2019-11-06 05:30 UTC, rafaelekol commented on app/src/main/java/io/horizontalsystems/feeratekit/demo/MainViewModel.kt
> +            .subscribe() { t -> rates.postValue(t) })
Can we split disposables with new lines, for better reading

2019-11-06 05:50 UTC, rafaelekol commented on feeratekit/src/main/kotlin/io/horizontalsystems/feeratekit/storage/EnumConverter.kt
>      }
we can delete this class, if it not used anymore

2019-11-06 09:35 UTC, omurovch commented on feeratekit/src/main/kotlin/io/horizontalsystems/feeratekit/providers/BaseFeeRateProvider.kt
> +        storage.getFeeRate(this.coin)?.let {
return can be moved to here

2019-11-06 10:45 UTC, omurovch commented on feeratekit/build.gradle
> +    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.0'
let's remove coroutine dependencies

2019-11-06 10:51 UTC, omurovch approved these changes

2019-11-06 10:59 UTC, merged